export const FETCH_QUOTES_REQUEST='FETCH_QUOTES_REQUEST'
export const FETCH_QUOTES_SUCCESS='FETCH_QUOTES_SUCCESS'
export const ERROR_QUOTES='ERROR_QUOTES'
export const POST_QUOTES_REQUEST='POST_QUOTES_REQUEST'
export const DELETE_QUOTES_REQUEST='DELETE_QUOTES_REQUEST'

